In [16]:
import numpy as np
a = np.arange(15).reshape(3,5)
print a
print "shape",a.shape
print "ndim", a.ndim
print "dtype", a.dtype
print "itemsize", a.itemsize
print "size", a.size
print "type(a)", type(a)


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
shape (3, 5)
ndim 2
dtype int64
itemsize 8
size 15
type(a) <type 'numpy.ndarray'>


In [19]:
import numpy as np
a = np.array([2,3,4])
a.dtype

b = np.array([2.,3.,4.])
b.dtype

dtype('float64')

In [26]:
import numpy as np
np.zeros( (3,4) )
np.ones((2,3,4), dtype=np.int16)
np.empty( (2,3) )
np.arange(10, 30, 5)
np.arange(0, 2, 0.3)


array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [33]:
import numpy as np
np.linspace(0, 2, 9)
x = np.linspace(0, 2*np.pi, 100)
f = np.sin(x)


In [37]:
import numpy as np
a = np.arange(12).reshape(4, 3)
a = np.arange(24).reshape(2, 3, 4)
print (np.arange(10000))

[   0    1    2 ..., 9997 9998 9999]


In [45]:
import numpy as np
a = np.array([20, 30, 40, 50])
b = np.arange(4)
print(b)
c = a - b
print(c)
print(b**2)
print(10*np.sin(a))
print(a<35)

[0 1 2 3]
[20 29 38 47]
[0 1 4 9]
[ 9.12945251 -9.88031624  7.4511316  -2.62374854]
[ True  True False False]


In [49]:
A = np.array([[1, 1],[0, 1]])
B = np.array([[2,0], [3, 4]])
A.dot(B)
np.dot(A, B)
A.shape

(2, 2)

In [58]:
a = np.ones((2, 3), dtype=int)
b = np.random.random((2, 3))
a *= 3
b += a

In [64]:
a = np.ones(3, dtype=np.int32)
b = np.linspace(0, np.pi, 3)
b.dtype.name

c = a + b
c

array([ 1.        ,  2.57079633,  4.14159265])

In [82]:
a = np.random.random((2,3))
print(a.sum())
print(a.min())
print(a.max())

b = np.arange(12).reshape(3,4)
print(b)
print(b.sum(axis=0))
m = b.sum(axis=1)
print m.shape
b.cumsum(axis=1)

3.50577681579
0.360660839677
0.95559317706
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[12 15 18 21]
(3,)


array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

In [88]:
B = np.arange(3)
print(B)
print np.exp(B)
print np.sqrt(B)
C = np.array([2., -1., 4.])
np.add(B, C)

[0 1 2]
[ 1.          2.71828183  7.3890561 ]
[ 0.          1.          1.41421356]


array([ 2.,  0.,  6.])

In [99]:
def f(x,y):
    return 10*x+y

b = np.fromfunction(f, (5, 4), dtype=int)
print b
print b[2,3]
print b[0:5, 1]
print "xxxx", b[1,2,...]


[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]
 [40 41 42 43]]
23
[ 1 11 21 31 41]
xxxx 12


In [103]:
c = np.array([[[0,1,2],[10, 12, 13]],[[100, 101, 102],[110,112,113]]])
c.shape


array([[  2,  13],
       [102, 113]])

In [105]:
for row in b:
    print(row)

[0 1 2 3]

[10 11 12 13]

[20 21 22 23]

[30 31 32 33]

[40 41 42 43]



In [133]:
a = np.floor(10*np.random.random((3,4)))
print a
print a.ravel().shape
print a.T
a.resize(2, 6)
print a
a.reshape(3, -1)

[[ 2.  3.  7.  3.]
 [ 3.  9.  0.  3.]
 [ 0.  5.  2.  4.]]
(12,)
[[ 2.  3.  0.]
 [ 3.  9.  5.]
 [ 7.  0.  2.]
 [ 3.  3.  4.]]
[[ 2.  3.  7.  3.  3.  9.]
 [ 0.  3.  0.  5.  2.  4.]]


array([[ 2.,  3.,  7.,  3.],
       [ 3.,  9.,  0.,  3.],
       [ 0.,  5.,  2.,  4.]])

In [144]:
a = np.floor(10*np.random.random((2,2)))
print a
b = np.floor(10*np.random.random((2,2)))
print b

np.vstack((a, b))
np.hstack((a, b))
c = b
print id(a), id(b), id(c)
print c.flags



[[ 2.  1.]
 [ 1.  1.]]
[[ 1.  7.]
 [ 7.  5.]]
66734480 66733760 66733760
  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False


TypeError: 'module' object is not iterable