In [37]:
import tensorflow as tf
v1 = tf.constant([1., 2., 3., 4.])
v2 = tf.constant([4., 3., 2., 1.])
sess = tf.InteractiveSession()
print tf.greater(v1, v2).eval()
print tf.where(tf.greater(v1, v2), v1, v2).eval()

[False False  True  True]
[ 4.  3.  3.  4.]


In [38]:
import tensorflow as tf
from numpy.random import RandomState

x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_ = tf.placeholder(tf.float32, shape=(None, 1), name="y-input")

w1 = tf.Variable(tf.random_normal([2,1], stddev=1, seed=1))
y = tf.matmul(x, w1)

In [45]:
loss_less = 1
loss_more = 1000
loss = tf.reduce_sum(tf.where(tf.greater(y, y_), (y-y_)*loss_more, (y_-y) * loss_less ))
train_step = tf.train.AdamOptimizer(0.001).minimize(loss)

In [46]:
rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size,2)
Y = [[x1+x2+rdm.rand()/10.0-0.05] for (x1, x2) in X]

with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    batch_size = 8
    STEPS = 5000
    for i in range(STEPS):
        start = (i*batch_size) % dataset_size
        end = min(start+batch_size, dataset_size)
        sess.run(train_step, feed_dict={x:X[start:end], y_:Y[start:end]})
        if i%1000 == 0:
            print i, "steps:\n", sess.run(w1)
    print i, "steps:\n", sess.run(w1)
    ww = sess.run(w1)

    print "foward propagation:", sess.run(tf.matmul(x, ww), feed_dict={x:[[-0.01, 0.01]]})
        

0 steps:
[[-0.81231821]
 [ 1.48359871]]
1000 steps:
[[-1.00663936]
 [ 0.99975079]]
2000 steps:
[[-0.89243895]
 [ 0.97022849]]
3000 steps:
[[-0.67336702]
 [ 0.96329486]]
4000 steps:
[[-0.32197747]
 [ 0.9526661 ]]
4999 steps:
[[ 0.19476356]
 [ 0.93936056]]
foward propagation: [[ 0.00744597]]
