In [43]:
import tensorflow as tf
sess = tf.Session()
w1 = tf.Variable(tf.random_normal([2, 3], stddev=1, seed=1))
w2 = tf.Variable(tf.random_normal([3, 1], stddev=1, seed=1))
x = tf.placeholder(tf.float32, shape=(None, 2), name="x-input")
y_ = tf.placeholder(tf.float32, shape=(None, 1), name="y-input")

a = tf.matmul(x, w1)
y = tf.matmul(a, w2)

print(1e-10 == 0.000000001)

False


In [29]:
## loss fuction and optimizition methoed
cross_entropy = -tf.reduce_mean(y_ * tf.log(tf.clip_by_value(y, 1e-10, 1.0)))
train_step = tf.train.AdamOptimizer(0.001).minimize(cross_entropy)

In [32]:
## generate samples
from numpy.random import RandomState
rdm = RandomState(1)
dataset_size = 128
X = rdm.rand(dataset_size, 2)
Y = [[int(x1+x2 < 1)] for (x1, x2) in X]
print(X)
print(Y)


[[  4.17022005e-01   7.20324493e-01]
 [  1.14374817e-04   3.02332573e-01]
 [  1.46755891e-01   9.23385948e-02]
 [  1.86260211e-01   3.45560727e-01]
 [  3.96767474e-01   5.38816734e-01]
 [  4.19194514e-01   6.85219500e-01]
 [  2.04452250e-01   8.78117436e-01]
 [  2.73875932e-02   6.70467510e-01]
 [  4.17304802e-01   5.58689828e-01]
 [  1.40386939e-01   1.98101489e-01]
 [  8.00744569e-01   9.68261576e-01]
 [  3.13424178e-01   6.92322616e-01]
 [  8.76389152e-01   8.94606664e-01]
 [  8.50442114e-02   3.90547832e-02]
 [  1.69830420e-01   8.78142503e-01]
 [  9.83468338e-02   4.21107625e-01]
 [  9.57889530e-01   5.33165285e-01]
 [  6.91877114e-01   3.15515631e-01]
 [  6.86500928e-01   8.34625672e-01]
 [  1.82882773e-02   7.50144315e-01]
 [  9.88861089e-01   7.48165654e-01]
 [  2.80443992e-01   7.89279328e-01]
 [  1.03226007e-01   4.47893526e-01]
 [  9.08595503e-01   2.93614148e-01]
 [  2.87775339e-01   1.30028572e-01]
 [  1.93669579e-02   6.78835533e-01]
 [  2.11628116e-01   2.65546659e-01]
 

In [37]:
## the training process
with tf.Session() as sess:
    init_op = tf.global_variables_initializer()
    sess.run(init_op)
    #print sess.run(w1)
    #print sess.run(w2)
    STEPS = 5000
    batch_size = 8
    for i in range(STEPS):
        start = (i*batch_size) % dataset_size
        end = min(start+batch_size, dataset_size)
        sess.run(train_step, feed_dict={x:X[start:end], y_:Y[start:end]})
        if i% 1000 == 0:
            total_cross_entropy = sess.run(cross_entropy, feed_dict={x:X, y_:Y})
            print sess.run(y, feed_dict={x:X[0:10]})
            print("After %d training step(s), cross entropy on all data is %g" % (i, total_cross_entropy))
    print "\n\n\n", "="*50, "\n\n"
    print sess.run(w1)
    print sess.run(w2)

[[ 2.76284432]
 [ 0.65738058]
 [ 0.62205219]
 [ 1.28580117]
 [ 2.31022167]
 [ 2.69278955]
 [ 2.49542785]
 [ 1.53574789]
 [ 2.41237974]
 [ 0.83361721]]
After 0 training step(s), cross entropy on all data is 0.0674925
[[ 5.97476864]
 [ 1.50576854]
 [ 1.30032754]
 [ 2.78723836]
 [ 4.95514202]
 [ 5.81244898]
 [ 5.54269075]
 [ 3.49469233]
 [ 5.17171717]
 [ 1.79036891]]
After 1000 training step(s), cross entropy on all data is 0.0163385
[[ 8.21904087]
 [ 2.08657336]
 [ 1.78065503]
 [ 3.83539295]
 [ 6.80904436]
 [ 7.99379349]
 [ 7.65107393]
 [ 4.83873749]
 [ 7.10618544]
 [ 2.46064234]]
After 2000 training step(s), cross entropy on all data is 0.00907547
[[ 9.82039356]
 [ 2.50913954]
 [ 2.11903811]
 [ 4.58392382]
 [ 8.1279068 ]
 [ 9.5491991 ]
 [ 9.16961956]
 [ 5.81455231]
 [ 8.48211384]
 [ 2.93770552]]
After 3000 training step(s), cross entropy on all data is 0.00714436
[[ 11.70862579]
 [  3.02404308]
 [  2.50916886]
 [  5.46786547]
 [  9.6749754 ]
 [ 11.38111401]
 [ 10.98911381]
 [  6.9994936